# Generated by Django 6.0.1 on 2026-01-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_comment_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
