# Generated by Django 6.0.1 on 2026-02-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_comment_news'),
        ('news', '0009_alter_comment_is_published'),
    ]

    operations = [
    ]
