# Generated by Django 6.0.1 on 2026-02-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_comment_options_alter_comment_is_published_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsImage',
        ),
    ]
