# Generated by Django 6.0.1 on 2026-01-30 05:52

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='О нас / О компании / История', max_length=100, verbose_name='О нас')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('image', models.ImageField(null=True, upload_to='teams/', verbose_name='Фото')),
                ('biog', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Биография')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('exp', models.CharField(max_length=100, verbose_name='Опыт')),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название соцсети')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на аккаунт')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.team', verbose_name='Сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='ImageShotsTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название фотки')),
                ('img', models.ImageField(upload_to='shotsImage')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.team', verbose_name='Сотрудник')),
            ],
        ),
    ]
