# Generated by Django 6.0.1 on 2026-01-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_1', models.CharField(max_length=20, verbose_name='Телефон 1')),
                ('phone_2', models.CharField(blank=True, max_length=20, verbose_name='Телефон 2')),
                ('phone_3', models.CharField(blank=True, max_length=20, verbose_name='Телефон 3')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('map_embed', models.TextField(help_text='Вставь iframe-код карты (Google / Яндекс)', verbose_name='Код карты (iframe)')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
